FROM gradle:5.6.2-jdk8 AS BUILD
ARG HB_WORK_DIR_NAME
ARG HB_ABSOLUTE_PATH_UPLOADS_DIR
ARG HB_ABSOLUTE_PATH_IMAGES_DIR
RUN mkdir $HB_WORK_DIR_NAME
WORKDIR /$HB_WORK_DIR_NAME
COPY . .
RUN gradle build

FROM openjdk:8
ARG HB_WORK_DIR_NAME
ARG HB_ABSOLUTE_PATH_UPLOADS_DIR
ARG HB_ABSOLUTE_PATH_IMAGES_DIR
RUN mkdir $HB_WORK_DIR_NAME
RUN mkdir $HB_WORK_DIR_NAME/build
RUN mkdir $HB_ABSOLUTE_PATH_UPLOADS_DIR
RUN mkdir $HB_ABSOLUTE_PATH_IMAGES_DIR
WORKDIR /$HB_WORK_DIR_NAME
EXPOSE 8080
COPY --from=BUILD /$HB_WORK_DIR_NAME/build/libs/high-blog-api-0.0.1.jar build
CMD ["java", "-jar", "build/high-blog-api-0.0.1.jar"]