spring:
    datasource:
        url: ${HB_DB_URL}
        username: ${HB_DB_USERNAME}
        password: ${HB_DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
        open-in-view: false
        show-sql: true
    liquibase:
        change-log: classpath:config/liquibase_ext/master.xml
    servlet:
        multipart:
            max-file-size: 10MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${HB_MAIL_USERNAME}
        password: ${HB_MAIL_PASSWORD}
        protocol: smtp
        properties.mail.smtp:
            auth: true
            starttls.enable: true

server:
    servlet:
        encoding:
            charset: UTF-8
            force: true
    ssl:
        key-store: ${HB_SSL_KEY_STORE}
        key-store-type: ${HB_SSL_KEY_STORE_TYPE}
        key-store-password: ${HB_SSL_KEY_STORE_PASSWORD}
        key-alias: ${HB_SSL_KEY_ALIAS}
        enabled: true
    port: 8443


application:
    jwt:
        secret-key: ${HB_JWT_SECRET_KEY}
        issuer: ${HB_JWT_ISSUER}
        expiration: ${HB_JWT_EXPIRATION}
        refresh-expiration: ${HB_JWT_REFRESH_EXPIRATION}
    file-upload:
        allowed-image-extensions:
            - jpg
            - jepg
            - png
            - gif
        root-dir: ${HB_ABSOLUTE_PATH_UPLOADS_DIR:/home/ninhthuan/uploads}
        images-sub-dir: ${HB_IMAGES_SUB_DIR:images}
    resource-template:
        registration-email-template: classpath:./templates/registration_email_template.html
    cors:
        allowed-origin: ${HB_ALLOWED_ORIGIN}
    paypal:
        client-id: ${HB_PAYPAL_CLIENT_ID}
        client-secret: ${HB_PAYPAL_CLIENT_SECRET}
        environment: ${HB_PAYPAL_ENVIRONMENT}
